release check if exists

diff --git a/.github/workflows/ghpages-release.yml b/.github/workflows/ghpages-release.yml
--- a/.github/workflows/ghpages-release.yml
+++ b/.github/workflows/ghpages-release.yml
@@ -43,7 +43,15 @@ jobs:
 
       - name: Check that the GitHub release doesn't already exist
         run: |
-          echo "TODO: Abort if release tag already exists"
+          GHJSON=$(gh release view ${{env.templateRelease}} --json name)
+
+          if [ -z "$GHJSON" ]
+          then
+                echo "Release not found - great"
+          else
+                echo "Release already exists - aborting"
+                exit 1
+          fi
 
       - name: Install Bicep
         shell: pwsh
